node{
  checkout scm
	docker.withRegistry('https://registry.cn-shanghai.aliyuncs.com/', 'aliyunDockerRegistry'){
	  def buildImageTag='bimbox_app_build:latest'
	  docker.build(buildImageTag,'--file ./jenkins/Dockerfile.build .')
        sh 'echo $PWD'
        shd 'mkdir -p $PWD/dist'
		def buildImage=docker.image(buildImageTag, '$PWD/:/home/node/bimbox/dist')
		buildImage.inside {
		  stage('Install'){
            echo '=========================Install packages=============================='
            sh 'mkdir -p dist'
            sh 'touch dist/build.test'
            // sh 'cnpm install'
          }
          stage('Build'){
            echo '==================================build==================================='
            sh 'touch ./dist/build.test'
            // sh 'cnpm run build'
          }
		}

    stage('Deploy'){
      echo '==================================deploy=================================='
      def deployImageTag='registry.cn-shanghai.aliyuncs.com/bimbox/bimserver-bimbox:3.0'
      def deployImage=docker.build(deployImageTag, '--file ./jenkins/Dockerfile.deploy --rm .')

      // docker.push(deployImageTag)
      deployImage.inside {
        sh 'pwd'
        sh 'ls -la ./dist'
        sh 'ls -la .'
      }
    }
	}
} 