node{
  checkout scm
	docker.withRegistry('https://registry.cn-shanghai.aliyuncs.com/', 'aliyunDockerRegistry'){
	  def buildImageTag='bimbox_app_build:latest'
	  docker.build(buildImageTag,'--file ./jenkins/Dockerfile.build .')

		def buildImage=docker.image(buildImageTag)
		buildImage.inside('-v $PWD/:/home/node/bimbox') {
		  stage('Install'){
            echo '=========================Install packages=============================='
            sh 'pwd'
            sh 'rm -fr ./dist'
            sh 'ls -la .'
            sh 'mkdir -p ./dist/bimbox'            
          }
      stage('Build'){
        echo '==================================build==================================='
        sh 'touch ./dist/bimbox/build.test'
        // sh 'cnpm run build'
      }
		}

    stage('Deploy'){
      echo '==================================deploy=================================='
      def deployImageTag='registry.cn-shanghai.aliyuncs.com/bimbox/bimserver-bimbox:3.0'
      def deployImage=docker.build(deployImageTag, '--file ./jenkins/Dockerfile.deploy --rm .')

      // docker.push(deployImageTag)
      deployImage.inside() {
        sh 'pwd'
        sh 'ls -la ./dist'
        sh 'ls -la .'
      }
    }
	}
}